Algoritmo "20"
//
//
// Descrição   :Desenvolva um programa que leia um número inteiro e mostre
// se ele é PAR ou ÍMPAR.

// Autor(a)    : Ricardo Lima
// Data atual  : 04/02/2023
Var
       n:inteiro


Inicio

   escreval("Digite um numero qualquer:")
   leia(n)

   se (N % 2 = 0) entao
      escreval("o numero ",N," é par")
   senao
      escreval("o numero ",N," é impar")
   fimSe


Fimalgoritmo