Algoritmo "42"
//
// Descrição :

// Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!

// Autor(a)  : Ricardo Lima
// Data atual  : 17/02/2023
Var

   n,c:inteiro

Inicio
   c<-1
   escreva("digite um numero:")
   leia(n)
   enquanto (c<=n) faca
      escreva(c)
      c <- c+1
   fimenquanto
   escreval(" Acabou!")


Fimalgoritmo