Algoritmo "48"
//
//
// Descrição   :
// Faça um programa que leia 7 números inteiros e no final mostre o somatório entre eles.


// Autor(a)    : Ricardo Lima
// Data atual  : 18/02/2023
Var

   c,s,n:inteiro

Inicio
   c <-7
   enquanto (c>=1)faca
      escreval("Digite um numero:")
      leia (n)
      s <- s +n
      c <-c -1
   fimenquanto
   escreval()
      escreva("a soma dos numeros é",s)

Fimalgoritmo