Algoritmo "conversão de moedas"





Var
        dolar,reais:real
       cont,quant:inteiro

Inicio
  cont<-1
   Escreva("quantas vezes vc quer converter? ")
   leia(quant)
   enquanto (cont <=quant)faca
    escreva("quantos reais eu tenho R$?")
       leia(reais)
       dolar  <- reais/2.20//cotação do dólar
    escreval("vou poder comprar um total de US$",dolar:5:2," dolares")
    cont <- cont+1
    fimenquanto
        
        
        

Fimalgoritmo